version: '3.3'

services: 

  emby: 
    image: emby/embyserver:latest
    volumes:
      - "~/emby/config:/config"
      - "/downloads/movies:/mnt/movies"
      - "/downloads/tv:/mnt/tv"
    restart: always
    environment:
      PGID: 1000
      PUID: 1000
    ports: 
      - "8096:8096" # HTTP
      - "8920:8920" # HTTPS
 
  # replace sabnzbs with your favourite torrent client (transmission is very popular, jackett is a popular torrent proxy)
  sabnzbd:
    image: linuxserver/sabnzbd
    volumes: 
      - "~/sabnzbd/config:/config"
      - "/downloads/downloads:/downloads"
      - "/downloads/incomplete-downloads:/incomplete-downloads"
    restart: always
    environment:
      TZ: "Asia/Jerusalem"
      PGID: 1000
      PUID: 1000
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
      - "9090:9090"
      
  deluge:
    image: linuxserver/deluge
    restart: always
    environment:
      TZ: "Asia/Jerusalem"
      PGID: 1000
      PUID: 1000
    ports: 
      - "8112:8112"  
    volumes:
      - ~/deluge/config:/config
      - /downloads/downloads:/downloads
      
  jackett:
    image: linuxserver/jackett
    restart: always
    environment:
      TZ: "Asia/Jerusalem"
      PGID: 1000
      PUID: 1000
    ports: 
      - "9117:9117"
    volumes:
      - "~/jackett/config:/config"
      - "/blackhole:/downloads"
    links:
      - sabnzbd
      - deluge

  radarr:
    image: linuxserver/radarr
    restart: always
    environment:
      TZ: "Asia/Jerusalem"
      PGID: 1000
      PUID: 1000
    ports: 
      - "7878:7878"
    volumes:
      - "~/radarr/config:/config"
      - "/downloads/downloads:/downloads"
      - "/downloads/movies:/movies"
    links:
      - sabnzbd
      - deluge
      - jackett

  sonarr:
    image: linuxserver/sonarr
    restart: always
    environment:
      TZ: "Asia/Jerusalem"
      PGID: 1000
      PUID: 1000
    ports: 
      - "8989:8989"
    volumes:
      - "~/sonarr/config:/config"
      - "/downloads/downloads:/downloads"
      - "/downloads/tv:/tv"
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - sabnzbd
      - deluge
      - jackett

  nginx:
    image: nginx:alpine 
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf:ro"
